add_test( [==[Basic functionality]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Basic functionality]==]  )
set_tests_properties( [==[Basic functionality]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Audio concepts]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Audio concepts]==]  )
set_tests_properties( [==[Audio concepts]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Memory management]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Memory management]==]  )
set_tests_properties( [==[Memory management]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Rapid Audio Engine]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Rapid Audio Engine]==]  )
set_tests_properties( [==[Rapid Audio Engine]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Rapid Natural Language Processing]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Rapid Natural Language Processing]==]  )
set_tests_properties( [==[Rapid Natural Language Processing]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Rapid Track Management]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Rapid Track Management]==]  )
set_tests_properties( [==[Rapid Track Management]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Rapid DAW Integration]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Rapid DAW Integration]==]  )
set_tests_properties( [==[Rapid DAW Integration]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Rapid Development Performance]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Rapid Development Performance]==]  )
set_tests_properties( [==[Rapid Development Performance]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
add_test( [==[Rapid Development Demo Scenario]==] C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test/Release/MixMindTests.exe [==[Rapid Development Demo Scenario]==]  )
set_tests_properties( [==[Rapid Development Demo Scenario]==] PROPERTIES WORKING_DIRECTORY C:/Users/antoi/Desktop/reaper-ai-pilot/build_rapid_test)
set( MixMindTests_TESTS [==[Basic functionality]==] [==[Audio concepts]==] [==[Memory management]==] [==[Rapid Audio Engine]==] [==[Rapid Natural Language Processing]==] [==[Rapid Track Management]==] [==[Rapid DAW Integration]==] [==[Rapid Development Performance]==] [==[Rapid Development Demo Scenario]==])
